// Mocks generated by Mockito 5.4.6 from annotations
// in kashew/test/views/add_topic_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i9;

import 'package:flutter/material.dart' as _i5;
import 'package:kashew/database/repositories/category_repository.dart' as _i4;
import 'package:kashew/database/repositories/setting_repository.dart' as _i2;
import 'package:kashew/database/repositories/topic_repository.dart' as _i6;
import 'package:kashew/l10n/app_localizations.dart' as _i14;
import 'package:kashew/models/category_model.dart' as _i11;
import 'package:kashew/models/currency_model.dart' as _i3;
import 'package:kashew/models/topic_model.dart' as _i13;
import 'package:kashew/view_models/category_viewmodel.dart' as _i10;
import 'package:kashew/view_models/currency_viewmodel.dart' as _i7;
import 'package:kashew/view_models/topic_viewmodel.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSettingsRepository_0 extends _i1.SmartFake
    implements _i2.SettingsRepository {
  _FakeSettingsRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCurrencyModel_1 extends _i1.SmartFake implements _i3.CurrencyModel {
  _FakeCurrencyModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategoryRepository_2 extends _i1.SmartFake
    implements _i4.CategoryRepository {
  _FakeCategoryRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIconData_3 extends _i1.SmartFake implements _i5.IconData {
  _FakeIconData_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTopicRepository_4 extends _i1.SmartFake
    implements _i6.TopicRepository {
  _FakeTopicRepository_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CurrencyViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockCurrencyViewModel extends _i1.Mock implements _i7.CurrencyViewModel {
  @override
  _i2.SettingsRepository get settingsRepo =>
      (super.noSuchMethod(
            Invocation.getter(#settingsRepo),
            returnValue: _FakeSettingsRepository_0(
              this,
              Invocation.getter(#settingsRepo),
            ),
            returnValueForMissingStub: _FakeSettingsRepository_0(
              this,
              Invocation.getter(#settingsRepo),
            ),
          )
          as _i2.SettingsRepository);

  @override
  List<_i3.CurrencyModel> get currencies =>
      (super.noSuchMethod(
            Invocation.getter(#currencies),
            returnValue: <_i3.CurrencyModel>[],
            returnValueForMissingStub: <_i3.CurrencyModel>[],
          )
          as List<_i3.CurrencyModel>);

  @override
  _i3.CurrencyModel get defaultCurrency =>
      (super.noSuchMethod(
            Invocation.getter(#defaultCurrency),
            returnValue: _FakeCurrencyModel_1(
              this,
              Invocation.getter(#defaultCurrency),
            ),
            returnValueForMissingStub: _FakeCurrencyModel_1(
              this,
              Invocation.getter(#defaultCurrency),
            ),
          )
          as _i3.CurrencyModel);

  @override
  set settingsRepo(_i2.SettingsRepository? value) => super.noSuchMethod(
    Invocation.setter(#settingsRepo, value),
    returnValueForMissingStub: null,
  );

  @override
  set defaultCurrency(_i3.CurrencyModel? value) => super.noSuchMethod(
    Invocation.setter(#defaultCurrency, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.Future<void> loadDefaultCurrency() =>
      (super.noSuchMethod(
            Invocation.method(#loadDefaultCurrency, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void setDefaultCurrency(_i3.CurrencyModel? model) => super.noSuchMethod(
    Invocation.method(#setDefaultCurrency, [model]),
    returnValueForMissingStub: null,
  );

  @override
  void selectCurrency(_i3.CurrencyModel? model) => super.noSuchMethod(
    Invocation.method(#selectCurrency, [model]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.CurrencyModel getCurrencyFromCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrencyFromCode, [code]),
            returnValue: _FakeCurrencyModel_1(
              this,
              Invocation.method(#getCurrencyFromCode, [code]),
            ),
            returnValueForMissingStub: _FakeCurrencyModel_1(
              this,
              Invocation.method(#getCurrencyFromCode, [code]),
            ),
          )
          as _i3.CurrencyModel);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [CategoryViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryViewModel extends _i1.Mock implements _i10.CategoryViewModel {
  @override
  _i4.CategoryRepository get categoryRepo =>
      (super.noSuchMethod(
            Invocation.getter(#categoryRepo),
            returnValue: _FakeCategoryRepository_2(
              this,
              Invocation.getter(#categoryRepo),
            ),
            returnValueForMissingStub: _FakeCategoryRepository_2(
              this,
              Invocation.getter(#categoryRepo),
            ),
          )
          as _i4.CategoryRepository);

  @override
  set categories(List<_i11.CategoryModel>? value) => super.noSuchMethod(
    Invocation.setter(#categories, value),
    returnValueForMissingStub: null,
  );

  @override
  set selectedCategory(_i11.CategoryModel? value) => super.noSuchMethod(
    Invocation.setter(#selectedCategory, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.Future<void> loadCategories() =>
      (super.noSuchMethod(
            Invocation.method(#loadCategories, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void selectCategory(_i11.CategoryModel? model) => super.noSuchMethod(
    Invocation.method(#selectCategory, [model]),
    returnValueForMissingStub: null,
  );

  @override
  void selectCategoryById(int? categoryId) => super.noSuchMethod(
    Invocation.method(#selectCategoryById, [categoryId]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.IconData getIconByCategoryId(int? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#getIconByCategoryId, [categoryId]),
            returnValue: _FakeIconData_3(
              this,
              Invocation.method(#getIconByCategoryId, [categoryId]),
            ),
            returnValueForMissingStub: _FakeIconData_3(
              this,
              Invocation.method(#getIconByCategoryId, [categoryId]),
            ),
          )
          as _i5.IconData);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TopicViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopicViewModel extends _i1.Mock implements _i12.TopicViewModel {
  @override
  _i6.TopicRepository get topicRepo =>
      (super.noSuchMethod(
            Invocation.getter(#topicRepo),
            returnValue: _FakeTopicRepository_4(
              this,
              Invocation.getter(#topicRepo),
            ),
            returnValueForMissingStub: _FakeTopicRepository_4(
              this,
              Invocation.getter(#topicRepo),
            ),
          )
          as _i6.TopicRepository);

  @override
  bool get isTopicLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isTopicLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isTopicAdding =>
      (super.noSuchMethod(
            Invocation.getter(#isTopicAdding),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isError =>
      (super.noSuchMethod(
            Invocation.getter(#isError),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set topics(List<_i13.TopicModel>? value) => super.noSuchMethod(
    Invocation.setter(#topics, value),
    returnValueForMissingStub: null,
  );

  @override
  set isTopicLoading(bool? value) => super.noSuchMethod(
    Invocation.setter(#isTopicLoading, value),
    returnValueForMissingStub: null,
  );

  @override
  set isTopicAdding(bool? value) => super.noSuchMethod(
    Invocation.setter(#isTopicAdding, value),
    returnValueForMissingStub: null,
  );

  @override
  set isError(bool? value) => super.noSuchMethod(
    Invocation.setter(#isError, value),
    returnValueForMissingStub: null,
  );

  @override
  set errorMessage(String? value) => super.noSuchMethod(
    Invocation.setter(#errorMessage, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void setSelectedTopic(_i13.TopicModel? model, {bool? notify = false}) =>
      super.noSuchMethod(
        Invocation.method(#setSelectedTopic, [model], {#notify: notify}),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> loadTopics() =>
      (super.noSuchMethod(
            Invocation.method(#loadTopics, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateLastUpdated(_i13.TopicModel? model) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastUpdated, [model]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<int> addTopic(
    _i14.AppLocalizations? lang,
    _i13.TopicModel? model,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addTopic, [lang, model]),
            returnValue: _i8.Future<int>.value(0),
            returnValueForMissingStub: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> saveTopic(
    _i14.AppLocalizations? lang,
    _i13.TopicModel? model,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveTopic, [lang, model]),
            returnValue: _i8.Future<int>.value(0),
            returnValueForMissingStub: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> deleteTopic(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTopic, [id]),
            returnValue: _i8.Future<int>.value(0),
            returnValueForMissingStub: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
