// Mocks generated by Mockito 5.4.6 from annotations
// in kashew/test/views/add_expense_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:ui' as _i12;

import 'package:flutter/material.dart' as _i4;
import 'package:kashew/database/repositories/category_repository.dart' as _i3;
import 'package:kashew/database/repositories/expense_repository.dart' as _i2;
import 'package:kashew/database/repositories/home_repository.dart' as _i6;
import 'package:kashew/database/repositories/topic_repository.dart' as _i5;
import 'package:kashew/l10n/app_localizations.dart' as _i11;
import 'package:kashew/models/category_model.dart' as _i14;
import 'package:kashew/models/expense_group_model.dart' as _i8;
import 'package:kashew/models/expense_model.dart' as _i9;
import 'package:kashew/models/topic_model.dart' as _i16;
import 'package:kashew/view_models/category_viewmodel.dart' as _i13;
import 'package:kashew/view_models/expense_viewmodel.dart' as _i7;
import 'package:kashew/view_models/home_viewmodel.dart' as _i17;
import 'package:kashew/view_models/topic_viewmodel.dart' as _i15;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeExpenseRepository_0 extends _i1.SmartFake
    implements _i2.ExpenseRepository {
  _FakeExpenseRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategoryRepository_1 extends _i1.SmartFake
    implements _i3.CategoryRepository {
  _FakeCategoryRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIconData_2 extends _i1.SmartFake implements _i4.IconData {
  _FakeIconData_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTopicRepository_3 extends _i1.SmartFake
    implements _i5.TopicRepository {
  _FakeTopicRepository_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHomeRepository_4 extends _i1.SmartFake
    implements _i6.HomeRepository {
  _FakeHomeRepository_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDateTime_5 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ExpenseViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpenseViewModel extends _i1.Mock implements _i7.ExpenseViewModel {
  @override
  _i2.ExpenseRepository get expenseRepo =>
      (super.noSuchMethod(
            Invocation.getter(#expenseRepo),
            returnValue: _FakeExpenseRepository_0(
              this,
              Invocation.getter(#expenseRepo),
            ),
            returnValueForMissingStub: _FakeExpenseRepository_0(
              this,
              Invocation.getter(#expenseRepo),
            ),
          )
          as _i2.ExpenseRepository);

  @override
  bool get isExpenseLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isExpenseLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isExpenseAdding =>
      (super.noSuchMethod(
            Invocation.getter(#isExpenseAdding),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isError =>
      (super.noSuchMethod(
            Invocation.getter(#isError),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set groupExpenses(List<_i8.ExpenseGroup>? value) => super.noSuchMethod(
    Invocation.setter(#groupExpenses, value),
    returnValueForMissingStub: null,
  );

  @override
  set recentExpenses(List<_i9.ExpenseModel>? value) => super.noSuchMethod(
    Invocation.setter(#recentExpenses, value),
    returnValueForMissingStub: null,
  );

  @override
  set isExpenseLoading(bool? value) => super.noSuchMethod(
    Invocation.setter(#isExpenseLoading, value),
    returnValueForMissingStub: null,
  );

  @override
  set isExpenseAdding(bool? value) => super.noSuchMethod(
    Invocation.setter(#isExpenseAdding, value),
    returnValueForMissingStub: null,
  );

  @override
  set isError(bool? value) => super.noSuchMethod(
    Invocation.setter(#isError, value),
    returnValueForMissingStub: null,
  );

  @override
  set errorTitle(String? value) => super.noSuchMethod(
    Invocation.setter(#errorTitle, value),
    returnValueForMissingStub: null,
  );

  @override
  set errorAmount(String? value) => super.noSuchMethod(
    Invocation.setter(#errorAmount, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void setCurrentTopicId(int? topicId) => super.noSuchMethod(
    Invocation.method(#setCurrentTopicId, [topicId]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> loadRecentExpenses() =>
      (super.noSuchMethod(
            Invocation.method(#loadRecentExpenses, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> loadExpenses(int? topicId) =>
      (super.noSuchMethod(
            Invocation.method(#loadExpenses, [topicId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  List<_i8.ExpenseGroup> groupExpensesByDate(
    List<_i9.ExpenseModel>? expenses,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#groupExpensesByDate, [expenses]),
            returnValue: <_i8.ExpenseGroup>[],
            returnValueForMissingStub: <_i8.ExpenseGroup>[],
          )
          as List<_i8.ExpenseGroup>);

  @override
  _i10.Future<int> addExpenseByValue(
    _i11.AppLocalizations? lang,
    String? title,
    String? amount,
    DateTime? date,
    String? note,
    String? currency,
    int? categoryId,
    int? topicId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addExpenseByValue, [
              lang,
              title,
              amount,
              date,
              note,
              currency,
              categoryId,
              topicId,
            ]),
            returnValue: _i10.Future<int>.value(0),
            returnValueForMissingStub: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  _i10.Future<int> addExpense(_i9.ExpenseModel? expense) =>
      (super.noSuchMethod(
            Invocation.method(#addExpense, [expense]),
            returnValue: _i10.Future<int>.value(0),
            returnValueForMissingStub: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  _i10.Future<int> updateExpenseByValue(
    _i11.AppLocalizations? lang,
    int? expenseId,
    String? title,
    String? amount,
    DateTime? date,
    String? note,
    String? currency,
    int? categoryId,
    int? topicId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateExpenseByValue, [
              lang,
              expenseId,
              title,
              amount,
              date,
              note,
              currency,
              categoryId,
              topicId,
            ]),
            returnValue: _i10.Future<int>.value(0),
            returnValueForMissingStub: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  _i10.Future<int> updateExpense(_i9.ExpenseModel? expense) =>
      (super.noSuchMethod(
            Invocation.method(#updateExpense, [expense]),
            returnValue: _i10.Future<int>.value(0),
            returnValueForMissingStub: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  _i10.Future<int> deleteExpense(int? expenseId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteExpense, [expenseId]),
            returnValue: _i10.Future<int>.value(0),
            returnValueForMissingStub: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  double getTotalExpenses(int? topicId) =>
      (super.noSuchMethod(
            Invocation.method(#getTotalExpenses, [topicId]),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  double getTotalExpensesByTopicId(
    List<_i9.ExpenseModel>? expenses,
    int? topicId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTotalExpensesByTopicId, [expenses, topicId]),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  void addExpenseLocally(_i9.ExpenseModel? expense) => super.noSuchMethod(
    Invocation.method(#addExpenseLocally, [expense]),
    returnValueForMissingStub: null,
  );

  @override
  void updateExpenseLocally(_i9.ExpenseModel? updatedExpense) =>
      super.noSuchMethod(
        Invocation.method(#updateExpenseLocally, [updatedExpense]),
        returnValueForMissingStub: null,
      );

  @override
  void deleteExpenseLocally(int? expenseId) => super.noSuchMethod(
    Invocation.method(#deleteExpenseLocally, [expenseId]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [CategoryViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryViewModel extends _i1.Mock implements _i13.CategoryViewModel {
  @override
  _i3.CategoryRepository get categoryRepo =>
      (super.noSuchMethod(
            Invocation.getter(#categoryRepo),
            returnValue: _FakeCategoryRepository_1(
              this,
              Invocation.getter(#categoryRepo),
            ),
            returnValueForMissingStub: _FakeCategoryRepository_1(
              this,
              Invocation.getter(#categoryRepo),
            ),
          )
          as _i3.CategoryRepository);

  @override
  set categories(List<_i14.CategoryModel>? value) => super.noSuchMethod(
    Invocation.setter(#categories, value),
    returnValueForMissingStub: null,
  );

  @override
  set selectedCategory(_i14.CategoryModel? value) => super.noSuchMethod(
    Invocation.setter(#selectedCategory, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i10.Future<void> loadCategories() =>
      (super.noSuchMethod(
            Invocation.method(#loadCategories, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void selectCategory(_i14.CategoryModel? model) => super.noSuchMethod(
    Invocation.method(#selectCategory, [model]),
    returnValueForMissingStub: null,
  );

  @override
  void selectCategoryById(int? categoryId) => super.noSuchMethod(
    Invocation.method(#selectCategoryById, [categoryId]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.IconData getIconByCategoryId(int? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#getIconByCategoryId, [categoryId]),
            returnValue: _FakeIconData_2(
              this,
              Invocation.method(#getIconByCategoryId, [categoryId]),
            ),
            returnValueForMissingStub: _FakeIconData_2(
              this,
              Invocation.method(#getIconByCategoryId, [categoryId]),
            ),
          )
          as _i4.IconData);

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TopicViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopicViewModel extends _i1.Mock implements _i15.TopicViewModel {
  @override
  _i5.TopicRepository get topicRepo =>
      (super.noSuchMethod(
            Invocation.getter(#topicRepo),
            returnValue: _FakeTopicRepository_3(
              this,
              Invocation.getter(#topicRepo),
            ),
            returnValueForMissingStub: _FakeTopicRepository_3(
              this,
              Invocation.getter(#topicRepo),
            ),
          )
          as _i5.TopicRepository);

  @override
  bool get isTopicLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isTopicLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isTopicAdding =>
      (super.noSuchMethod(
            Invocation.getter(#isTopicAdding),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isError =>
      (super.noSuchMethod(
            Invocation.getter(#isError),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set topics(List<_i16.TopicModel>? value) => super.noSuchMethod(
    Invocation.setter(#topics, value),
    returnValueForMissingStub: null,
  );

  @override
  set isTopicLoading(bool? value) => super.noSuchMethod(
    Invocation.setter(#isTopicLoading, value),
    returnValueForMissingStub: null,
  );

  @override
  set isTopicAdding(bool? value) => super.noSuchMethod(
    Invocation.setter(#isTopicAdding, value),
    returnValueForMissingStub: null,
  );

  @override
  set isError(bool? value) => super.noSuchMethod(
    Invocation.setter(#isError, value),
    returnValueForMissingStub: null,
  );

  @override
  set errorMessage(String? value) => super.noSuchMethod(
    Invocation.setter(#errorMessage, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void setSelectedTopic(_i16.TopicModel? model, {bool? notify = false}) =>
      super.noSuchMethod(
        Invocation.method(#setSelectedTopic, [model], {#notify: notify}),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> loadTopics() =>
      (super.noSuchMethod(
            Invocation.method(#loadTopics, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> updateLastUpdated(_i16.TopicModel? model) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastUpdated, [model]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<int> addTopic(
    _i11.AppLocalizations? lang,
    _i16.TopicModel? model,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addTopic, [lang, model]),
            returnValue: _i10.Future<int>.value(0),
            returnValueForMissingStub: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  _i10.Future<int> saveTopic(
    _i11.AppLocalizations? lang,
    _i16.TopicModel? model,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveTopic, [lang, model]),
            returnValue: _i10.Future<int>.value(0),
            returnValueForMissingStub: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  _i10.Future<int> deleteTopic(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTopic, [id]),
            returnValue: _i10.Future<int>.value(0),
            returnValueForMissingStub: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [HomeViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeViewModel extends _i1.Mock implements _i17.HomeViewModel {
  @override
  _i6.HomeRepository get homeRepo =>
      (super.noSuchMethod(
            Invocation.getter(#homeRepo),
            returnValue: _FakeHomeRepository_4(
              this,
              Invocation.getter(#homeRepo),
            ),
            returnValueForMissingStub: _FakeHomeRepository_4(
              this,
              Invocation.getter(#homeRepo),
            ),
          )
          as _i6.HomeRepository);

  @override
  DateTime get today =>
      (super.noSuchMethod(
            Invocation.getter(#today),
            returnValue: _FakeDateTime_5(this, Invocation.getter(#today)),
            returnValueForMissingStub: _FakeDateTime_5(
              this,
              Invocation.getter(#today),
            ),
          )
          as DateTime);

  @override
  DateTime get monthStart =>
      (super.noSuchMethod(
            Invocation.getter(#monthStart),
            returnValue: _FakeDateTime_5(this, Invocation.getter(#monthStart)),
            returnValueForMissingStub: _FakeDateTime_5(
              this,
              Invocation.getter(#monthStart),
            ),
          )
          as DateTime);

  @override
  DateTime get nextMonthStart =>
      (super.noSuchMethod(
            Invocation.getter(#nextMonthStart),
            returnValue: _FakeDateTime_5(
              this,
              Invocation.getter(#nextMonthStart),
            ),
            returnValueForMissingStub: _FakeDateTime_5(
              this,
              Invocation.getter(#nextMonthStart),
            ),
          )
          as DateTime);

  @override
  set homeRepo(_i6.HomeRepository? value) => super.noSuchMethod(
    Invocation.setter(#homeRepo, value),
    returnValueForMissingStub: null,
  );

  @override
  set today(DateTime? value) => super.noSuchMethod(
    Invocation.setter(#today, value),
    returnValueForMissingStub: null,
  );

  @override
  set monthStart(DateTime? value) => super.noSuchMethod(
    Invocation.setter(#monthStart, value),
    returnValueForMissingStub: null,
  );

  @override
  set nextMonthStart(DateTime? value) => super.noSuchMethod(
    Invocation.setter(#nextMonthStart, value),
    returnValueForMissingStub: null,
  );

  @override
  set totalMonthlyExpense(double? value) => super.noSuchMethod(
    Invocation.setter(#totalMonthlyExpense, value),
    returnValueForMissingStub: null,
  );

  @override
  set categoryId(int? value) => super.noSuchMethod(
    Invocation.setter(#categoryId, value),
    returnValueForMissingStub: null,
  );

  @override
  set topCategory(String? value) => super.noSuchMethod(
    Invocation.setter(#topCategory, value),
    returnValueForMissingStub: null,
  );

  @override
  set topCategoryAmount(double? value) => super.noSuchMethod(
    Invocation.setter(#topCategoryAmount, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i10.Future<void> loadStats() =>
      (super.noSuchMethod(
            Invocation.method(#loadStats, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
