// Mocks generated by Mockito 5.4.6 from annotations
// in kashew/test/views/language_only_list_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i3;

import 'package:kashew/database/repositories/setting_repository.dart' as _i2;
import 'package:kashew/models/language_model.dart' as _i4;
import 'package:kashew/view_models/language_viewmodel.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSettingsRepository_0 extends _i1.SmartFake
    implements _i2.SettingsRepository {
  _FakeSettingsRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocale_1 extends _i1.SmartFake implements _i3.Locale {
  _FakeLocale_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLanguageModel_2 extends _i1.SmartFake implements _i4.LanguageModel {
  _FakeLanguageModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LanguageViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockLanguageViewModel extends _i1.Mock implements _i5.LanguageViewModel {
  MockLanguageViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SettingsRepository get settingsRepo =>
      (super.noSuchMethod(
            Invocation.getter(#settingsRepo),
            returnValue: _FakeSettingsRepository_0(
              this,
              Invocation.getter(#settingsRepo),
            ),
          )
          as _i2.SettingsRepository);

  @override
  _i3.Locale get locale =>
      (super.noSuchMethod(
            Invocation.getter(#locale),
            returnValue: _FakeLocale_1(this, Invocation.getter(#locale)),
          )
          as _i3.Locale);

  @override
  List<_i4.LanguageModel> get languages =>
      (super.noSuchMethod(
            Invocation.getter(#languages),
            returnValue: <_i4.LanguageModel>[],
          )
          as List<_i4.LanguageModel>);

  @override
  set settingsRepo(_i2.SettingsRepository? value) => super.noSuchMethod(
    Invocation.setter(#settingsRepo, value),
    returnValueForMissingStub: null,
  );

  @override
  set languages(List<_i4.LanguageModel>? value) => super.noSuchMethod(
    Invocation.setter(#languages, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.LanguageModel getLanguage(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#getLanguage, [code]),
            returnValue: _FakeLanguageModel_2(
              this,
              Invocation.method(#getLanguage, [code]),
            ),
          )
          as _i4.LanguageModel);

  @override
  _i6.Future<void> loadLanguage() =>
      (super.noSuchMethod(
            Invocation.method(#loadLanguage, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> changeLanguage(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#changeLanguage, [code]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void addListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
