// Mocks generated by Mockito 5.4.6 from annotations
// in kashew/test/views/settings_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i4;

import 'package:kashew/database/repositories/setting_repository.dart' as _i2;
import 'package:kashew/models/currency_model.dart' as _i3;
import 'package:kashew/models/language_model.dart' as _i5;
import 'package:kashew/view_models/currency_viewmodel.dart' as _i6;
import 'package:kashew/view_models/language_viewmodel.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSettingsRepository_0 extends _i1.SmartFake
    implements _i2.SettingsRepository {
  _FakeSettingsRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCurrencyModel_1 extends _i1.SmartFake implements _i3.CurrencyModel {
  _FakeCurrencyModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocale_2 extends _i1.SmartFake implements _i4.Locale {
  _FakeLocale_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLanguageModel_3 extends _i1.SmartFake implements _i5.LanguageModel {
  _FakeLanguageModel_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CurrencyViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockCurrencyViewModel extends _i1.Mock implements _i6.CurrencyViewModel {
  MockCurrencyViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SettingsRepository get settingsRepo =>
      (super.noSuchMethod(
            Invocation.getter(#settingsRepo),
            returnValue: _FakeSettingsRepository_0(
              this,
              Invocation.getter(#settingsRepo),
            ),
          )
          as _i2.SettingsRepository);

  @override
  List<_i3.CurrencyModel> get currencies =>
      (super.noSuchMethod(
            Invocation.getter(#currencies),
            returnValue: <_i3.CurrencyModel>[],
          )
          as List<_i3.CurrencyModel>);

  @override
  _i3.CurrencyModel get defaultCurrency =>
      (super.noSuchMethod(
            Invocation.getter(#defaultCurrency),
            returnValue: _FakeCurrencyModel_1(
              this,
              Invocation.getter(#defaultCurrency),
            ),
          )
          as _i3.CurrencyModel);

  @override
  set settingsRepo(_i2.SettingsRepository? value) => super.noSuchMethod(
    Invocation.setter(#settingsRepo, value),
    returnValueForMissingStub: null,
  );

  @override
  set defaultCurrency(_i3.CurrencyModel? value) => super.noSuchMethod(
    Invocation.setter(#defaultCurrency, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i7.Future<void> loadDefaultCurrency() =>
      (super.noSuchMethod(
            Invocation.method(#loadDefaultCurrency, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void setDefaultCurrency(_i3.CurrencyModel? model) => super.noSuchMethod(
    Invocation.method(#setDefaultCurrency, [model]),
    returnValueForMissingStub: null,
  );

  @override
  void selectCurrency(_i3.CurrencyModel? model) => super.noSuchMethod(
    Invocation.method(#selectCurrency, [model]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.CurrencyModel getCurrencyFromCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrencyFromCode, [code]),
            returnValue: _FakeCurrencyModel_1(
              this,
              Invocation.method(#getCurrencyFromCode, [code]),
            ),
          )
          as _i3.CurrencyModel);

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [LanguageViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockLanguageViewModel extends _i1.Mock implements _i8.LanguageViewModel {
  MockLanguageViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SettingsRepository get settingsRepo =>
      (super.noSuchMethod(
            Invocation.getter(#settingsRepo),
            returnValue: _FakeSettingsRepository_0(
              this,
              Invocation.getter(#settingsRepo),
            ),
          )
          as _i2.SettingsRepository);

  @override
  _i4.Locale get locale =>
      (super.noSuchMethod(
            Invocation.getter(#locale),
            returnValue: _FakeLocale_2(this, Invocation.getter(#locale)),
          )
          as _i4.Locale);

  @override
  List<_i5.LanguageModel> get languages =>
      (super.noSuchMethod(
            Invocation.getter(#languages),
            returnValue: <_i5.LanguageModel>[],
          )
          as List<_i5.LanguageModel>);

  @override
  set settingsRepo(_i2.SettingsRepository? value) => super.noSuchMethod(
    Invocation.setter(#settingsRepo, value),
    returnValueForMissingStub: null,
  );

  @override
  set languages(List<_i5.LanguageModel>? value) => super.noSuchMethod(
    Invocation.setter(#languages, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.LanguageModel getLanguage(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#getLanguage, [code]),
            returnValue: _FakeLanguageModel_3(
              this,
              Invocation.method(#getLanguage, [code]),
            ),
          )
          as _i5.LanguageModel);

  @override
  _i7.Future<void> loadLanguage() =>
      (super.noSuchMethod(
            Invocation.method(#loadLanguage, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> changeLanguage(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#changeLanguage, [code]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
