// Mocks generated by Mockito 5.4.6 from annotations
// in kashew/test/views/topic_only_list_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i7;

import 'package:kashew/database/repositories/topic_repository.dart' as _i2;
import 'package:kashew/l10n/app_localizations.dart' as _i6;
import 'package:kashew/models/topic_model.dart' as _i4;
import 'package:kashew/view_models/topic_viewmodel.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTopicRepository_0 extends _i1.SmartFake
    implements _i2.TopicRepository {
  _FakeTopicRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TopicViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopicViewModel extends _i1.Mock implements _i3.TopicViewModel {
  MockTopicViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TopicRepository get topicRepo =>
      (super.noSuchMethod(
            Invocation.getter(#topicRepo),
            returnValue: _FakeTopicRepository_0(
              this,
              Invocation.getter(#topicRepo),
            ),
          )
          as _i2.TopicRepository);

  @override
  bool get isTopicLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isTopicLoading),
            returnValue: false,
          )
          as bool);

  @override
  bool get isTopicAdding =>
      (super.noSuchMethod(Invocation.getter(#isTopicAdding), returnValue: false)
          as bool);

  @override
  bool get isError =>
      (super.noSuchMethod(Invocation.getter(#isError), returnValue: false)
          as bool);

  @override
  set topics(List<_i4.TopicModel>? value) => super.noSuchMethod(
    Invocation.setter(#topics, value),
    returnValueForMissingStub: null,
  );

  @override
  set isTopicLoading(bool? value) => super.noSuchMethod(
    Invocation.setter(#isTopicLoading, value),
    returnValueForMissingStub: null,
  );

  @override
  set isTopicAdding(bool? value) => super.noSuchMethod(
    Invocation.setter(#isTopicAdding, value),
    returnValueForMissingStub: null,
  );

  @override
  set isError(bool? value) => super.noSuchMethod(
    Invocation.setter(#isError, value),
    returnValueForMissingStub: null,
  );

  @override
  set errorMessage(String? value) => super.noSuchMethod(
    Invocation.setter(#errorMessage, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setSelectedTopic(_i4.TopicModel? model, {bool? notify = false}) =>
      super.noSuchMethod(
        Invocation.method(#setSelectedTopic, [model], {#notify: notify}),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> loadTopics() =>
      (super.noSuchMethod(
            Invocation.method(#loadTopics, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateLastUpdated(_i4.TopicModel? model) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastUpdated, [model]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<int> addTopic(_i6.AppLocalizations? lang, _i4.TopicModel? model) =>
      (super.noSuchMethod(
            Invocation.method(#addTopic, [lang, model]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> saveTopic(
    _i6.AppLocalizations? lang,
    _i4.TopicModel? model,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveTopic, [lang, model]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> deleteTopic(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTopic, [id]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
