// Mocks generated by Mockito 5.4.6 from annotations
// in kashew/test/view_models/category_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter/material.dart' as _i3;
import 'package:kashew/database/helper/database_helper.dart' as _i2;
import 'package:kashew/database/repositories/category_repository.dart' as _i4;
import 'package:kashew/models/category_model.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabaseHelper_0 extends _i1.SmartFake
    implements _i2.DatabaseHelper {
  _FakeDatabaseHelper_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIconData_1 extends _i1.SmartFake implements _i3.IconData {
  _FakeIconData_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i4.CategoryRepository {
  MockCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseHelper get dbHelper =>
      (super.noSuchMethod(
            Invocation.getter(#dbHelper),
            returnValue: _FakeDatabaseHelper_0(
              this,
              Invocation.getter(#dbHelper),
            ),
          )
          as _i2.DatabaseHelper);

  @override
  _i5.Future<List<_i6.CategoryModel>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i5.Future<List<_i6.CategoryModel>>.value(
              <_i6.CategoryModel>[],
            ),
          )
          as _i5.Future<List<_i6.CategoryModel>>);
}

/// A class which mocks [CategoryModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryModel extends _i1.Mock implements _i6.CategoryModel {
  MockCategoryModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get categoryName =>
      (super.noSuchMethod(
            Invocation.getter(#categoryName),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#categoryName),
            ),
          )
          as String);

  @override
  _i3.IconData get icon =>
      (super.noSuchMethod(
            Invocation.getter(#icon),
            returnValue: _FakeIconData_1(this, Invocation.getter(#icon)),
          )
          as _i3.IconData);

  @override
  Map<String, dynamic> toMap() =>
      (super.noSuchMethod(
            Invocation.method(#toMap, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
