// Mocks generated by Mockito 5.4.6 from annotations
// in kashew/test/view_models/expense_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:kashew/database/helper/database_helper.dart' as _i2;
import 'package:kashew/database/repositories/expense_repository.dart' as _i3;
import 'package:kashew/models/expense_group_model.dart' as _i7;
import 'package:kashew/models/expense_model.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabaseHelper_0 extends _i1.SmartFake
    implements _i2.DatabaseHelper {
  _FakeDatabaseHelper_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDateTime_1 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ExpenseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpenseRepository extends _i1.Mock implements _i3.ExpenseRepository {
  MockExpenseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseHelper get dbHelper =>
      (super.noSuchMethod(
            Invocation.getter(#dbHelper),
            returnValue: _FakeDatabaseHelper_0(
              this,
              Invocation.getter(#dbHelper),
            ),
          )
          as _i2.DatabaseHelper);

  @override
  _i4.Future<int> insertExpense(_i5.ExpenseModel? expense) =>
      (super.noSuchMethod(
            Invocation.method(#insertExpense, [expense]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i5.ExpenseModel>> getAllExpenses() =>
      (super.noSuchMethod(
            Invocation.method(#getAllExpenses, []),
            returnValue: _i4.Future<List<_i5.ExpenseModel>>.value(
              <_i5.ExpenseModel>[],
            ),
          )
          as _i4.Future<List<_i5.ExpenseModel>>);

  @override
  _i4.Future<List<_i5.ExpenseModel>> getExpensesById(int? topicId) =>
      (super.noSuchMethod(
            Invocation.method(#getExpensesById, [topicId]),
            returnValue: _i4.Future<List<_i5.ExpenseModel>>.value(
              <_i5.ExpenseModel>[],
            ),
          )
          as _i4.Future<List<_i5.ExpenseModel>>);

  @override
  _i4.Future<List<_i5.ExpenseModel>> getRecentExpenses() =>
      (super.noSuchMethod(
            Invocation.method(#getRecentExpenses, []),
            returnValue: _i4.Future<List<_i5.ExpenseModel>>.value(
              <_i5.ExpenseModel>[],
            ),
          )
          as _i4.Future<List<_i5.ExpenseModel>>);

  @override
  _i4.Future<int> updateExpense(_i5.ExpenseModel? expense, int? expenseId) =>
      (super.noSuchMethod(
            Invocation.method(#updateExpense, [expense, expenseId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteExpense(int? expenseId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteExpense, [expenseId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}

/// A class which mocks [ExpenseModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpenseModel extends _i1.Mock implements _i5.ExpenseModel {
  MockExpenseModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get title =>
      (super.noSuchMethod(
            Invocation.getter(#title),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#title),
            ),
          )
          as String);

  @override
  double get amount =>
      (super.noSuchMethod(Invocation.getter(#amount), returnValue: 0.0)
          as double);

  @override
  int get dbDateTime =>
      (super.noSuchMethod(Invocation.getter(#dbDateTime), returnValue: 0)
          as int);

  @override
  set id(int? value) => super.noSuchMethod(
    Invocation.setter(#id, value),
    returnValueForMissingStub: null,
  );

  @override
  set title(String? value) => super.noSuchMethod(
    Invocation.setter(#title, value),
    returnValueForMissingStub: null,
  );

  @override
  set amount(double? value) => super.noSuchMethod(
    Invocation.setter(#amount, value),
    returnValueForMissingStub: null,
  );

  @override
  set dbDateTime(int? value) => super.noSuchMethod(
    Invocation.setter(#dbDateTime, value),
    returnValueForMissingStub: null,
  );

  @override
  set categoryId(int? value) => super.noSuchMethod(
    Invocation.setter(#categoryId, value),
    returnValueForMissingStub: null,
  );

  @override
  set topicId(int? value) => super.noSuchMethod(
    Invocation.setter(#topicId, value),
    returnValueForMissingStub: null,
  );

  @override
  set note(String? value) => super.noSuchMethod(
    Invocation.setter(#note, value),
    returnValueForMissingStub: null,
  );

  @override
  set currency(String? value) => super.noSuchMethod(
    Invocation.setter(#currency, value),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> toMap() =>
      (super.noSuchMethod(
            Invocation.method(#toMap, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [ExpenseGroup].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpenseGroup extends _i1.Mock implements _i7.ExpenseGroup {
  MockExpenseGroup() {
    _i1.throwOnMissingStub(this);
  }

  @override
  DateTime get date =>
      (super.noSuchMethod(
            Invocation.getter(#date),
            returnValue: _FakeDateTime_1(this, Invocation.getter(#date)),
          )
          as DateTime);

  @override
  List<_i5.ExpenseModel> get expenses =>
      (super.noSuchMethod(
            Invocation.getter(#expenses),
            returnValue: <_i5.ExpenseModel>[],
          )
          as List<_i5.ExpenseModel>);

  @override
  set date(DateTime? value) => super.noSuchMethod(
    Invocation.setter(#date, value),
    returnValueForMissingStub: null,
  );

  @override
  set expenses(List<_i5.ExpenseModel>? value) => super.noSuchMethod(
    Invocation.setter(#expenses, value),
    returnValueForMissingStub: null,
  );
}
