// Mocks generated by Mockito 5.4.6 from annotations
// in kashew/test/view_models/topic_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:kashew/database/helper/database_helper.dart' as _i2;
import 'package:kashew/database/repositories/topic_repository.dart' as _i3;
import 'package:kashew/l10n/app_localizations.dart' as _i7;
import 'package:kashew/models/topic_model.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabaseHelper_0 extends _i1.SmartFake
    implements _i2.DatabaseHelper {
  _FakeDatabaseHelper_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TopicRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopicRepository extends _i1.Mock implements _i3.TopicRepository {
  MockTopicRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseHelper get dbHelper =>
      (super.noSuchMethod(
            Invocation.getter(#dbHelper),
            returnValue: _FakeDatabaseHelper_0(
              this,
              Invocation.getter(#dbHelper),
            ),
          )
          as _i2.DatabaseHelper);

  @override
  _i4.Future<int> insertTopic(_i5.TopicModel? topic) =>
      (super.noSuchMethod(
            Invocation.method(#insertTopic, [topic]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i5.TopicModel>> getLatestTopics() =>
      (super.noSuchMethod(
            Invocation.method(#getLatestTopics, []),
            returnValue: _i4.Future<List<_i5.TopicModel>>.value(
              <_i5.TopicModel>[],
            ),
          )
          as _i4.Future<List<_i5.TopicModel>>);

  @override
  _i4.Future<List<_i5.TopicModel>> getAllTopics() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTopics, []),
            returnValue: _i4.Future<List<_i5.TopicModel>>.value(
              <_i5.TopicModel>[],
            ),
          )
          as _i4.Future<List<_i5.TopicModel>>);

  @override
  _i4.Future<int> updateTopic(_i5.TopicModel? topic) =>
      (super.noSuchMethod(
            Invocation.method(#updateTopic, [topic]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteTopic(int? topicId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTopic, [topicId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<Map<int, double>> getTotalExpensesTopicWise() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalExpensesTopicWise, []),
            returnValue: _i4.Future<Map<int, double>>.value(<int, double>{}),
          )
          as _i4.Future<Map<int, double>>);

  @override
  _i4.Future<double> getTotalExpenseForTopic(int? topicId) =>
      (super.noSuchMethod(
            Invocation.method(#getTotalExpenseForTopic, [topicId]),
            returnValue: _i4.Future<double>.value(0.0),
          )
          as _i4.Future<double>);
}

/// A class which mocks [TopicModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopicModel extends _i1.Mock implements _i5.TopicModel {
  MockTopicModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i6.dummyValue<String>(this, Invocation.getter(#name)),
          )
          as String);

  @override
  int get dbDateTime =>
      (super.noSuchMethod(Invocation.getter(#dbDateTime), returnValue: 0)
          as int);

  @override
  int get lastUpdated =>
      (super.noSuchMethod(Invocation.getter(#lastUpdated), returnValue: 0)
          as int);

  @override
  double get totalExpenses =>
      (super.noSuchMethod(Invocation.getter(#totalExpenses), returnValue: 0.0)
          as double);

  @override
  String get readableDateTime =>
      (super.noSuchMethod(
            Invocation.getter(#readableDateTime),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#readableDateTime),
            ),
          )
          as String);

  @override
  set id(int? value) => super.noSuchMethod(
    Invocation.setter(#id, value),
    returnValueForMissingStub: null,
  );

  @override
  set name(String? value) => super.noSuchMethod(
    Invocation.setter(#name, value),
    returnValueForMissingStub: null,
  );

  @override
  set description(String? value) => super.noSuchMethod(
    Invocation.setter(#description, value),
    returnValueForMissingStub: null,
  );

  @override
  set currency(String? value) => super.noSuchMethod(
    Invocation.setter(#currency, value),
    returnValueForMissingStub: null,
  );

  @override
  set dbDateTime(int? value) => super.noSuchMethod(
    Invocation.setter(#dbDateTime, value),
    returnValueForMissingStub: null,
  );

  @override
  set lastUpdated(int? value) => super.noSuchMethod(
    Invocation.setter(#lastUpdated, value),
    returnValueForMissingStub: null,
  );

  @override
  set isSystem(int? value) => super.noSuchMethod(
    Invocation.setter(#isSystem, value),
    returnValueForMissingStub: null,
  );

  @override
  set totalExpenses(double? value) => super.noSuchMethod(
    Invocation.setter(#totalExpenses, value),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> toMap() =>
      (super.noSuchMethod(
            Invocation.method(#toMap, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [AppLocalizations].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLocalizations extends _i1.Mock implements _i7.AppLocalizations {
  MockAppLocalizations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get localeName =>
      (super.noSuchMethod(
            Invocation.getter(#localeName),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#localeName),
            ),
          )
          as String);

  @override
  String get appTitle =>
      (super.noSuchMethod(
            Invocation.getter(#appTitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#appTitle),
            ),
          )
          as String);

  @override
  String get appVersion =>
      (super.noSuchMethod(
            Invocation.getter(#appVersion),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#appVersion),
            ),
          )
          as String);

  @override
  String get lblAppBarHome =>
      (super.noSuchMethod(
            Invocation.getter(#lblAppBarHome),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblAppBarHome),
            ),
          )
          as String);

  @override
  String get lblAppBarAddTopic =>
      (super.noSuchMethod(
            Invocation.getter(#lblAppBarAddTopic),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblAppBarAddTopic),
            ),
          )
          as String);

  @override
  String get lblAppBarEditTopic =>
      (super.noSuchMethod(
            Invocation.getter(#lblAppBarEditTopic),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblAppBarEditTopic),
            ),
          )
          as String);

  @override
  String get lblAppBarAddExpense =>
      (super.noSuchMethod(
            Invocation.getter(#lblAppBarAddExpense),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblAppBarAddExpense),
            ),
          )
          as String);

  @override
  String get lblAppBarSave =>
      (super.noSuchMethod(
            Invocation.getter(#lblAppBarSave),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblAppBarSave),
            ),
          )
          as String);

  @override
  String get lblAppBarTopicList =>
      (super.noSuchMethod(
            Invocation.getter(#lblAppBarTopicList),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblAppBarTopicList),
            ),
          )
          as String);

  @override
  String get lblAppBarSettings =>
      (super.noSuchMethod(
            Invocation.getter(#lblAppBarSettings),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblAppBarSettings),
            ),
          )
          as String);

  @override
  String get lblAppBarCurrencyList =>
      (super.noSuchMethod(
            Invocation.getter(#lblAppBarCurrencyList),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblAppBarCurrencyList),
            ),
          )
          as String);

  @override
  String get lblAppBarLanguageList =>
      (super.noSuchMethod(
            Invocation.getter(#lblAppBarLanguageList),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblAppBarLanguageList),
            ),
          )
          as String);

  @override
  String get lblLanguage =>
      (super.noSuchMethod(
            Invocation.getter(#lblLanguage),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblLanguage),
            ),
          )
          as String);

  @override
  String get lblCurrencies =>
      (super.noSuchMethod(
            Invocation.getter(#lblCurrencies),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblCurrencies),
            ),
          )
          as String);

  @override
  String get lblSubtitle =>
      (super.noSuchMethod(
            Invocation.getter(#lblSubtitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblSubtitle),
            ),
          )
          as String);

  @override
  String get lblTotalExpense =>
      (super.noSuchMethod(
            Invocation.getter(#lblTotalExpense),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblTotalExpense),
            ),
          )
          as String);

  @override
  String get lblMonthlyExpense =>
      (super.noSuchMethod(
            Invocation.getter(#lblMonthlyExpense),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblMonthlyExpense),
            ),
          )
          as String);

  @override
  String get lblTopics =>
      (super.noSuchMethod(
            Invocation.getter(#lblTopics),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblTopics),
            ),
          )
          as String);

  @override
  String get lblRecentExpenses =>
      (super.noSuchMethod(
            Invocation.getter(#lblRecentExpenses),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblRecentExpenses),
            ),
          )
          as String);

  @override
  String get lblViewAll =>
      (super.noSuchMethod(
            Invocation.getter(#lblViewAll),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblViewAll),
            ),
          )
          as String);

  @override
  String get lblSettings =>
      (super.noSuchMethod(
            Invocation.getter(#lblSettings),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblSettings),
            ),
          )
          as String);

  @override
  String get lblTopicName =>
      (super.noSuchMethod(
            Invocation.getter(#lblTopicName),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblTopicName),
            ),
          )
          as String);

  @override
  String get lblStartDate =>
      (super.noSuchMethod(
            Invocation.getter(#lblStartDate),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblStartDate),
            ),
          )
          as String);

  @override
  String get lblOptional =>
      (super.noSuchMethod(
            Invocation.getter(#lblOptional),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblOptional),
            ),
          )
          as String);

  @override
  String get lblDescription =>
      (super.noSuchMethod(
            Invocation.getter(#lblDescription),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblDescription),
            ),
          )
          as String);

  @override
  String get lblTopicHelp =>
      (super.noSuchMethod(
            Invocation.getter(#lblTopicHelp),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblTopicHelp),
            ),
          )
          as String);

  @override
  String get lblCurrency =>
      (super.noSuchMethod(
            Invocation.getter(#lblCurrency),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblCurrency),
            ),
          )
          as String);

  @override
  String get lblExpenseTitle =>
      (super.noSuchMethod(
            Invocation.getter(#lblExpenseTitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblExpenseTitle),
            ),
          )
          as String);

  @override
  String get lblExpenses =>
      (super.noSuchMethod(
            Invocation.getter(#lblExpenses),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblExpenses),
            ),
          )
          as String);

  @override
  String get lblExpenseAmount =>
      (super.noSuchMethod(
            Invocation.getter(#lblExpenseAmount),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblExpenseAmount),
            ),
          )
          as String);

  @override
  String get lblCategory =>
      (super.noSuchMethod(
            Invocation.getter(#lblCategory),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblCategory),
            ),
          )
          as String);

  @override
  String get lblNotes =>
      (super.noSuchMethod(
            Invocation.getter(#lblNotes),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblNotes),
            ),
          )
          as String);

  @override
  String get lblDate =>
      (super.noSuchMethod(
            Invocation.getter(#lblDate),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblDate),
            ),
          )
          as String);

  @override
  String get lblTopic =>
      (super.noSuchMethod(
            Invocation.getter(#lblTopic),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblTopic),
            ),
          )
          as String);

  @override
  String get lblNoTopics =>
      (super.noSuchMethod(
            Invocation.getter(#lblNoTopics),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblNoTopics),
            ),
          )
          as String);

  @override
  String get lblNoExpenses =>
      (super.noSuchMethod(
            Invocation.getter(#lblNoExpenses),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblNoExpenses),
            ),
          )
          as String);

  @override
  String get lblPreferences =>
      (super.noSuchMethod(
            Invocation.getter(#lblPreferences),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblPreferences),
            ),
          )
          as String);

  @override
  String get lblAppearance =>
      (super.noSuchMethod(
            Invocation.getter(#lblAppearance),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblAppearance),
            ),
          )
          as String);

  @override
  String get lblCurrencySettings =>
      (super.noSuchMethod(
            Invocation.getter(#lblCurrencySettings),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblCurrencySettings),
            ),
          )
          as String);

  @override
  String get lblAboutApp =>
      (super.noSuchMethod(
            Invocation.getter(#lblAboutApp),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblAboutApp),
            ),
          )
          as String);

  @override
  String get lblHelpSupport =>
      (super.noSuchMethod(
            Invocation.getter(#lblHelpSupport),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblHelpSupport),
            ),
          )
          as String);

  @override
  String get btnCreateTopic =>
      (super.noSuchMethod(
            Invocation.getter(#btnCreateTopic),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#btnCreateTopic),
            ),
          )
          as String);

  @override
  String get btnAddExpense =>
      (super.noSuchMethod(
            Invocation.getter(#btnAddExpense),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#btnAddExpense),
            ),
          )
          as String);

  @override
  String get menuEditTopic =>
      (super.noSuchMethod(
            Invocation.getter(#menuEditTopic),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#menuEditTopic),
            ),
          )
          as String);

  @override
  String get menuDeleteTopic =>
      (super.noSuchMethod(
            Invocation.getter(#menuDeleteTopic),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#menuDeleteTopic),
            ),
          )
          as String);

  @override
  String get hintTopic =>
      (super.noSuchMethod(
            Invocation.getter(#hintTopic),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#hintTopic),
            ),
          )
          as String);

  @override
  String get hintDescription =>
      (super.noSuchMethod(
            Invocation.getter(#hintDescription),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#hintDescription),
            ),
          )
          as String);

  @override
  String get hintToday =>
      (super.noSuchMethod(
            Invocation.getter(#hintToday),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#hintToday),
            ),
          )
          as String);

  @override
  String get hintExpenseTitle =>
      (super.noSuchMethod(
            Invocation.getter(#hintExpenseTitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#hintExpenseTitle),
            ),
          )
          as String);

  @override
  String get hintNotes =>
      (super.noSuchMethod(
            Invocation.getter(#hintNotes),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#hintNotes),
            ),
          )
          as String);

  @override
  String get hintAmount =>
      (super.noSuchMethod(
            Invocation.getter(#hintAmount),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#hintAmount),
            ),
          )
          as String);

  @override
  String get hintLinkTopic =>
      (super.noSuchMethod(
            Invocation.getter(#hintLinkTopic),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#hintLinkTopic),
            ),
          )
          as String);

  @override
  String get dialogTopicDeleteTitle =>
      (super.noSuchMethod(
            Invocation.getter(#dialogTopicDeleteTitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#dialogTopicDeleteTitle),
            ),
          )
          as String);

  @override
  String get dialogTopicDeleteMessage =>
      (super.noSuchMethod(
            Invocation.getter(#dialogTopicDeleteMessage),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#dialogTopicDeleteMessage),
            ),
          )
          as String);

  @override
  String get dialogDeleteConfirm =>
      (super.noSuchMethod(
            Invocation.getter(#dialogDeleteConfirm),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#dialogDeleteConfirm),
            ),
          )
          as String);

  @override
  String get dialogCancel =>
      (super.noSuchMethod(
            Invocation.getter(#dialogCancel),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#dialogCancel),
            ),
          )
          as String);

  @override
  String get dialogExpenseDeleteTitle =>
      (super.noSuchMethod(
            Invocation.getter(#dialogExpenseDeleteTitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#dialogExpenseDeleteTitle),
            ),
          )
          as String);

  @override
  String get dialogExpenseDeleteMessage =>
      (super.noSuchMethod(
            Invocation.getter(#dialogExpenseDeleteMessage),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#dialogExpenseDeleteMessage),
            ),
          )
          as String);

  @override
  String get errTopicName =>
      (super.noSuchMethod(
            Invocation.getter(#errTopicName),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#errTopicName),
            ),
          )
          as String);

  @override
  String get errExpenseTitle =>
      (super.noSuchMethod(
            Invocation.getter(#errExpenseTitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#errExpenseTitle),
            ),
          )
          as String);

  @override
  String get errExpenseAmount =>
      (super.noSuchMethod(
            Invocation.getter(#errExpenseAmount),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#errExpenseAmount),
            ),
          )
          as String);

  @override
  String get lblWelcome =>
      (super.noSuchMethod(
            Invocation.getter(#lblWelcome),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblWelcome),
            ),
          )
          as String);

  @override
  String get lblWelcomeMessage =>
      (super.noSuchMethod(
            Invocation.getter(#lblWelcomeMessage),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblWelcomeMessage),
            ),
          )
          as String);

  @override
  String get lblSelectLanguage =>
      (super.noSuchMethod(
            Invocation.getter(#lblSelectLanguage),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblSelectLanguage),
            ),
          )
          as String);

  @override
  String get lblSelectCurrency =>
      (super.noSuchMethod(
            Invocation.getter(#lblSelectCurrency),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblSelectCurrency),
            ),
          )
          as String);

  @override
  String get btnGetStarted =>
      (super.noSuchMethod(
            Invocation.getter(#btnGetStarted),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#btnGetStarted),
            ),
          )
          as String);

  @override
  String get lblTermsOfService =>
      (super.noSuchMethod(
            Invocation.getter(#lblTermsOfService),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblTermsOfService),
            ),
          )
          as String);

  @override
  String get lblTopCategory =>
      (super.noSuchMethod(
            Invocation.getter(#lblTopCategory),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblTopCategory),
            ),
          )
          as String);

  @override
  String get lblThisMonth =>
      (super.noSuchMethod(
            Invocation.getter(#lblThisMonth),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#lblThisMonth),
            ),
          )
          as String);

  @override
  String get tooltipKUnit =>
      (super.noSuchMethod(
            Invocation.getter(#tooltipKUnit),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#tooltipKUnit),
            ),
          )
          as String);

  @override
  String get snackFailToSave =>
      (super.noSuchMethod(
            Invocation.getter(#snackFailToSave),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#snackFailToSave),
            ),
          )
          as String);
}
